In [1]:
import numpy as np

In [2]:
l = [1, 2, 3, -4, -7, 32]

In [3]:
a = np.array(l)

In [4]:
print(a)

[ 1  2  3 -4 -7 32]


In [5]:
l[::2]

[1, 3, -7]

---

In [15]:
a[2:4]   #differing from lists, you aren't creating another array

array([80, 80])

In [16]:
b = a[2:4]

In [17]:
print(b)

[80 80]


In [18]:
b[:] = 70

In [19]:
print(b)

[70 70]


In [20]:
print(a)

[ 1  2 70 70 -7 32]


In [21]:
c = a.copy()

In [24]:
print(c)

[ 0  2 70 70 -7 32]


In [23]:
c[0] = 0

In [25]:
print(c, a)

[ 0  2 70 70 -7 32] [ 1  2 70 70 -7 32]
