In [2]:
import numpy as np

In [3]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [4]:
a_revenue = np.array(revenue)
a_expenses = np.array(expenses)

In [5]:
#profit for each month

In [6]:
#profit = []

#for i in range(0, len(revenue)):
#    profit.append(revenue[i] - expenses[i])
#print(profit)

profit = a_revenue - a_expenses
profit.round(2)
print(profit)

[ 2522.67  1911.39 -3707.79 -2914.31  -599.92  7265.24  8210.55  3944.97
  3328.39 -2238.65   659.6  11629.54]


In [7]:
#profit after tax for each month (30% tax rate)

In [8]:
# profit_taxed = []

# for i in range(0, len(profit)):
#     profit_taxed.append(round(profit[i] * 0.7, 2))
# print(profit_taxed)

profit_taxed = profit * 0.7
profit_taxed_round = profit_taxed.round(2)
print(profit_taxed_round)

[ 1765.87  1337.97 -2595.45 -2040.02  -419.94  5085.67  5747.38  2761.48
  2329.87 -1567.06   461.72  8140.68]


In [9]:
#profit margin for each month (profit after tax / revenue)

In [10]:
# profit_margin = []

# for i in range(0, len(profit_taxed)):
#     profit_margin.append(round(100 * profit_taxed[i] / revenue[i], 2))
# print(profit_margin)

profit_margin = 100 * profit_taxed / a_revenue
profit_margin_round = profit_margin.round(2)
print(profit_margin_round)

[ 12.12  17.59 -30.14 -22.23  -5.21  62.74  49.99  28.28  22.61 -10.9
   4.31  52.75]


In [11]:
#good months (profit after tax > mean of the year) - bad months (profit after tax < mean of the year)

In [12]:
good_months = []
bad_months = []

mean_pat = sum(profit_taxed) / len(profit_taxed)

for i in range(0, len(profit_taxed)):
    if profit_taxed[i] > mean_pat:
        good_months.append(i + 1)
    else:
        bad_months.append(i + 1)
print(good_months)
print(bad_months)   

[1, 6, 7, 8, 9, 12]
[2, 3, 4, 5, 10, 11]


In [13]:
#best month (max profit after tax)

In [30]:
# best_month = max(profit_taxed)
# print(best_month)

for i in range(len(profit_taxed_round)):
    if profit_taxed_round[i] == profit_taxed_round.max():
        best_month = i + 1
print(best_month)

12


In [26]:
#worst month (min profit afters tax)

In [27]:
# worst_month = min(profit_taxed)
# print(worst_month)

for i in range(0, len(profit_taxed_round)):
    if profit_taxed_round[i] == profit_taxed_round.min():
        worst_month = i + 1
print(worst_month)

3


In [33]:
#Convert All Calculations
revenue_1000 = (a_revenue/1000).astype(int)
expenses_1000 = (a_expenses/1000).astype(int)
profit_1000 = (profit/1000).astype(int)
profit_taxed_1000 = (profit_taxed_round/1000).astype(int)
profit_margin_result = profit_margin_round.astype(int)

In [35]:
#Print Results
print("Revenue: ") 
print(revenue_1000)
print("Expenses: ") 
print(expenses_1000)
print("Profit: ")
print(profit_1000)
print("Profit after tax: ")
print(profit_taxed_1000)
print("Profit margin (%): ")
print(profit_margin_result)
print("Good months: ")
print(good_months)
print("Bad months: ")
print(bad_months)
print("Best month: ")
print(best_month)
print("Worst month: ")
print(worst_month)

Revenue: 
[14  7  8  9  8  8 11  9 10 14 10 15]
Expenses: 
[12  5 12 12  8  0  3  5  6 16 10  3]
Profit: 
[ 2  1 -3 -2  0  7  8  3  3 -2  0 11]
Profit after tax: 
[ 1  1 -2 -2  0  5  5  2  2 -1  0  8]
Profit margin (%): 
[ 12  17 -30 -22  -5  62  49  28  22 -10   4  52]
Good months: 
[1, 6, 7, 8, 9, 12]
Bad months: 
[2, 3, 4, 5, 10, 11]
Best month: 
12
Worst month: 
3
